### ISSUE TITLE
LCD's screen appears off-center when mounted

### ISSUE THREAD

**Issue by jaythomas** [HestiaPi/hestia-touch-case#1]
There is a blank portion of the LCD on the right side that makes it look off-center.

Sorry for the blurry pic:

![20191031_120355](https://user-images.githubusercontent.com/2344456/67965106-cb5e3500-fbd7-11e9-9f99-68ddff55c034.jpg)

This is an after-stock screen, but the issue appears on the original screen as well. Perhaps the back mounts can be adjusted to better align everything.

**Comment by gulliverrr** [comment]
I am pretty sure you are viewing the full LCD.
The actual LCD is not indeed "centered" and there is a gap on the right:
https://www.waveshare.com/w/upload/2/22/3.5inch-RPi-LCD-B-Manual-20.png
but the mounts are actually located and aligned with the frame to center it. Have you pushed the LCD all the way to touch the side mounts?
Measure the visible width with a ruler if it is 73.44mm, that is 2.89 in inches, taken from the above link.
I cannot know for the aftermarket one as these LCD appear with many "clones" with little changes like this or 180' degree flipped.

**Comment by jaythomas** [comment]
It's flush with the side mounts. Since the pi and thermostat board are mounted to the wall and backplate there isn't much wiggle room to adjust the screen unfortunately. I'll cross check the dimensions to the waveshare model and see what I can do, thanks.
