### ISSUE TITLE
Bottom wall screw

### ISSUE THREAD

**Issue by gulliverrr** [HestiaPi/hestia-touch-case#2]
Screw's head may block the cover to fully insert. Move the hole or make clearance on the partition.

**Comment by hestiahacker** [comment]
Is this in reference to the bottom screw that goes through the back plate?

It looks like the divider is about 17mm from the bottom corner and the center of that hole is about 14mm from that same corner.

Assuming I understand the issue correctly, would moving that hole down by 3mm address this issue?

**Comment by gulliverrr** [comment]
This is a leftover since the case was a 3-piece assembly. Please ignore. Closing...
